import cx_Oracle
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("data/processed/sentiment_themes.csv")

# Connect to Oracle DB
connection = cx_Oracle.connect("username/password@hostname:port/service_name")
cursor = connection.cursor()

# Create table (adjust types as needed)
cursor.execute("""
CREATE TABLE bank_reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank VARCHAR2(100),
    review_text CLOB,
    clean_text CLOB,
    rating NUMBER,
    sentiment VARCHAR2(20),
    keywords CLOB,
    review_date DATE
)
""")

# Insert data
for _, row in df.iterrows():
    cursor.execute("""
        INSERT INTO bank_reviews (bank, review_text, clean_text, rating, sentiment, keywords, review_date)
        VALUES (:1, :2, :3, :4, :5, :6, TO_DATE(:7, 'YYYY-MM-DD'))
    """, (row['bank'], row['review_text'], row['clean_text'], row['rating'], row['sentiment'],
          ", ".join(row['keywords']), str(row['date']).split(' ')[0]))

connection.commit()
cursor.close()
connection.close()
print("✅ Data inserted into Oracle DB.")
